version: "3.3"
services:
  httpd:
    container_name: apache
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
      - "./httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf"
      - "./serverchain.crt:/usr/local/apache2/conf/server.crt"
      - "./server.key:/usr/local/apache2/conf/server.key"
      - "./static-site:/srv"
      - "./themes:/srv/themes"
  orbeon:
    container_name: orbeon
    image: tiredofit/orbeon:latest
    ports:
      - "8081:8080"
    volumes:
      - "./orbeon.xml:/usr/local/tomcat/conf/Catalina/localhost/ROOT.xml"
      - "..:/usr/local/projects/numishare"
      - "..:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare"
      - "./exist-config.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/apps/numishare/exist-config.xml"
      - "./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./web.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/web.xml"
      - "./properties-local.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/properties-local.xml"
#      - "../ogc:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/numishare-projects/ogc"
      - "./log-orbeon:/usr/local/logs"
#      - "./orbeon-log4j.xml:/usr/local/tomcat/webapps/orbeon/WEB-INF/resources/config/log4j.xml"
  solr:
    container_name: solr
    image: solr:8.11
    ports:
      - "127.0.0.1:8983:8983"
    volumes:
      - solr-data:/var/solr
      - "../solr-home/1.6:/var/solr/data/numishare"
    command:
      - solr-precreate
      - gettingstarted
  exist:
    image: existdb/existdb:5.4.1
    container_name: exist
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
    volumes:
      #- type: volume
      #  source: exist-data
      #  target: /exist/data
      - type: volume
        source: exist-config
        target: /exist/config
  fuseki:
    image: stain/jena-fuseki:3.14.0
    container_name: fuseki
    ports:
      - 127.0.0.1:3030:3030
    environment:
      - ADMIN_PASSWORD
      - JVM_ARGS=-Xmx3g
    volumes:
      - fuseki-data:/fuseki

volumes:
  solr-data:
    driver: local
  exist-data:
    driver: local
  exist-config:
    driver: local
  fuseki-data:
    driver: local
